name: Docker CD

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Push
        uses: warchant/Publish-Docker-Github-Action@master
        with:
          name: warchantua/tezt
          workdir: alt-integration-grpc-service
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag_names: true
          snapshot: true
